---
schema:
  procedures: {}
  tables:
    deview_session:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - year
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        day:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: day
          order: 3
          size:
            - 0
        description:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: description
          order: 6
          size:
            - 0
        ends_at:
          data_type: timestamp
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: ends_at
          order: 8
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 2
          size:
            - 0
        slide_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: slide_url
          order: 10
          size:
            - 0
        starts_at:
          data_type: timestamp
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: starts_at
          order: 7
          size:
            - 0
        target:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: target
          order: 9
          size:
            - 0
        title:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: title
          order: 5
          size:
            - 0
        track:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: track
          order: 4
          size:
            - 0
        video_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: video_url
          order: 11
          size:
            - 0
        year:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: year
          order: 1
          size:
            - 0
      indices: []
      name: deview_session
      options: []
      order: 1
    deview_speaker:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - session_year
            - session_id
          match_type: ''
          name: deview_speaker_fk_session_year_session_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - year
            - id
          reference_table: deview_session
          type: FOREIGN KEY
      fields:
        email:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: email
          order: 8
          size:
            - 0
        facebook_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: facebook_url
          order: 10
          size:
            - 0
        github_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: github_url
          order: 11
          size:
            - 0
        id:
          data_type: serial
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        introduction:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: introduction
          order: 6
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 4
          size:
            - 0
        organization:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: organization
          order: 5
          size:
            - 0
        picture:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: picture
          order: 7
          size:
            - 0
        session_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: session_id
          order: 3
          size:
            - 0
        session_year:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: session_year
          order: 2
          size:
            - 0
        website_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: website_url
          order: 9
          size:
            - 0
      indices:
        - fields:
            - session_year
            - session_id
          name: deview_speaker_idx_session_year_session_id
          options: []
          type: NORMAL
      name: deview_speaker
      options: []
      order: 3
    deview_user:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        fb_token:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: fb_token
          order: 2
          size:
            - 0
        id:
          data_type: bigint
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 3
          size:
            - 0
        picture:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: picture
          order: 4
          size:
            - 0
      indices: []
      name: deview_user
      options: []
      order: 2
    deview_user_attendance:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: deview_user_attendance_fk_user_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: deview_user
          type: FOREIGN KEY
      fields:
        id:
          data_type: serial
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        session_day:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: session_day
          order: 4
          size:
            - 0
        session_year:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: session_year
          order: 3
          size:
            - 0
        user_id:
          data_type: bigint
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 2
          size:
            - 0
      indices:
        - fields:
            - user_id
          name: deview_user_attendance_idx_user_id
          options: []
          type: NORMAL
      name: deview_user_attendance
      options: []
      order: 4
    deview_user_schedule:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - session_year
            - session_id
          match_type: ''
          name: deview_user_schedule_fk_session_year_session_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - year
            - id
          reference_table: deview_session
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: deview_user_schedule_fk_user_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: deview_user
          type: FOREIGN KEY
      fields:
        id:
          data_type: serial
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        session_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: session_id
          order: 4
          size:
            - 0
        session_year:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: session_year
          order: 3
          size:
            - 0
        user_id:
          data_type: bigint
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 2
          size:
            - 0
      indices:
        - fields:
            - session_year
            - session_id
          name: deview_user_schedule_idx_session_year_session_id
          options: []
          type: NORMAL
        - fields:
            - user_id
          name: deview_user_schedule_idx_user_id
          options: []
          type: NORMAL
      name: deview_user_schedule
      options: []
      order: 5
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Session
      - Speaker
      - User
      - UserAttendance
      - UserSchedule
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
